[profile.default]
evm_version = 'london'
solc_version = '0.8.17'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[profile.stargazer_local]
src = 'src'
out = 'out'
libs = ['lib']
evm_version = 'berlin'
eth_rpc_url = 'http://localhost:1317/eth/rpc'