dir: "{{.InterfaceDir}}/mocks"
mockname: "{{.InterfaceNameCamel}}"
filename: "{{.InterfaceNameSnake}}.go"
outpkg: "mocks"
packages:
  pkg.berachain.dev/polaris/cosmos/x/evm/plugins/txpool:
    config:
      all: True
      recursive: True
      with-expecter: true