# SPDX-License-Identifier: BUSL-1.1
#
# Copyright (C) 2023, Berachain Foundation. All rights reserved.
# Use of this software is govered by the Business Source License included
# in the LICENSE file of this repository and at www.mariadb.com/bsl11.
#
# ANY USE OF THE LICENSED WORK IN VIOLATION OF THIS LICENSE WILL AUTOMATICALLY
# TERMINATE YOUR RIGHTS UNDER THIS LICENSE FOR THE CURRENT AND ALL OTHER
# VERSIONS OF THE LICENSED WORK.
#
# THIS LICENSE DOES NOT GRANT YOU ANY RIGHT IN ANY TRADEMARK OR LOGO OF
# LICENSOR OR ITS AFFILIATES (PROVIDED THAT YOU MAY USE A TRADEMARK OR LOGO OF
# LICENSOR AS EXPRESSLY REQUIRED BY THIS LICENSE).
#
# TO THE EXTENT PERMITTED BY APPLICABLE LAW, THE LICENSED WORK IS PROVIDED ON
# AN “AS IS” BASIS. LICENSOR HEREBY DISCLAIMS ALL WARRANTIES AND CONDITIONS,
# EXPRESS OR IMPLIED, INCLUDING (WITHOUT LIMITATION) WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND
# TITLE.

version: 2.1

executors:
  standard:
    docker:
      - image: cimg/go:1.20.1
        environment:
          FOUNDRY_COMMIT: e2fa2b5f8940d283f54df1ec701967276a934e97
    resource_class: xlarge
  machine:
      machine:
        image: ubuntu-2204:2022.04.2
      environment:
        architecture: "amd64"
        platform: "linux/amd64"
orbs:
  codecov: codecov/codecov@3.2.4

jobs:
  build:
    executor: standard
    steps:
      - setup
      - run:
          name: Build
          command: mage build
  lint:
    executor: standard
    steps:
      - setup
      - run:
          name: Lint
          command: mage lint
  test-unit:
    executor: standard
    steps:
      - setup
      - run:
          name: Test Unit
          command: mage testunitcover
      - codecov/upload:
          file: coverage-testunitcover.txt
          flags: "unit"
      - store_test_results:
          path: .
  test-unit-race:
    executor: standard
    steps:
      - setup
      - run:
          name: Test Unit Race
          command: mage testunitrace
      - store_test_results:
          path: .
  test-integration:
    executor: machine
    steps:
      - run:
          name: Upgrade Golang
          command: |
            sudo rm -rf $(which go)
            sudo apt update
            sudo apt install software-properties-common -y
            sudo add-apt-repository ppa:longsleep/golang-backports -y
            sudo apt update -y
            sudo apt install golang-go -y
      - setup
      - run:
          name: Test Integration
          command: mage testintegrationcover
      - codecov/upload:
          file: coverage-testintegrationcover.txt
          flags: "integration"
      - store_test_results:
          path: .
          

workflows:
  build_lint_test:
    jobs:
      - build
      - lint
      - test-unit
      - test-unit-race
      - test-integration

commands:
  setup: # Setup the test environment
    steps:
      - checkout
      # Setup Golang
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/home/circleci/go/pkg/mod"
            - "/home/circleci/go/pkg/bin"
      - run:
          name: Install Go Dependencies
          command: |
            go mod download
      - run:
          name: Install Go Tools
          command: |
            echo 'export PATH=/home/circleci/go/bin:"$PATH"' >> "$BASH_ENV"
            source "$BASH_ENV"
            go install github.com/magefile/mage
            go install github.com/onsi/ginkgo/v2/ginkgo
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/home/circleci/go/pkg/mod"
            - "/home/circleci/go/pkg/bin"
      # Setup Foundry
      - restore_cache:
          keys:
            - foundry-${FOUNDRY_COMMIT}
          paths:
            - "/home/circleci/.foundry/bin"
      - run:
          name: Install Foundryup
          command: |
            curl -L https://foundry.paradigm.xyz | bash || true
            echo 'export PATH=/home/circleci/.foundry/bin:"$PATH"' >> "$BASH_ENV"
            source "$BASH_ENV"
            foundryup
      - save_cache:
          key: foundry-${FOUNDRY_COMMIT}
          paths:
            - "/home/circleci/.foundry/bin"
