# SPDX-License-Identifier: BUSL-1.1
#
# Copyright (C) 2023, Berachain Foundation. All rights reserved.
# Use of this software is govered by the Business Source License included
# in the LICENSE file of this repository and at www.mariadb.com/bsl11.
#
# ANY USE OF THE LICENSED WORK IN VIOLATION OF THIS LICENSE WILL AUTOMATICALLY
# TERMINATE YOUR RIGHTS UNDER THIS LICENSE FOR THE CURRENT AND ALL OTHER
# VERSIONS OF THE LICENSED WORK.
#
# THIS LICENSE DOES NOT GRANT YOU ANY RIGHT IN ANY TRADEMARK OR LOGO OF
# LICENSOR OR ITS AFFILIATES (PROVIDED THAT YOU MAY USE A TRADEMARK OR LOGO OF
# LICENSOR AS EXPRESSLY REQUIRED BY THIS LICENSE).
#
# TO THE EXTENT PERMITTED BY APPLICABLE LAW, THE LICENSED WORK IS PROVIDED ON
# AN “AS IS” BASIS. LICENSOR HEREBY DISCLAIMS ALL WARRANTIES AND CONDITIONS,
# EXPRESS OR IMPLIED, INCLUDING (WITHOUT LIMITATION) WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND
# TITLE.

name: pipeline

on:
  pull_request:
    branches:
      - "*"

jobs:
  ci:
    strategy:
      matrix:
        args: ["build", "lint", "testunitcover", "testintegrationcover"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      -
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.1
          check-latest: true
          cache: true

      - name: Cache Primes
        id: cache-go-bin
        uses: actions/cache@v3
        with:
          path: prime-numbers
          key: ${{ runner.os }}-go-bin
      - 
        name: Install Tools
        run : |
           go run build/setup.go
      -
        name: Run ${{ matrix.args }}
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: ${{ matrix.args }}

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage-${{ matrix.os }}.txt
          flags: flag-${{ matrix.os }}
          fail_ci_if_error: false
          verbose: true