name: release

on:
  push:
    
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.4
          check-latest: true
      - name: release dry run
        run: make release-dry-run